### ISSUE TITLE
Issues with initial release of player-shops

### ISSUE THREAD

**Issue by CarlosEZS** [Chuckleberry-Finn/pz-shops#10] opened 2023-05-15 15:52 UTC
-snip

**Comment by ChuckTheSheep** [comment] 2023-05-17 00:50
Wallet Issues:
- [ ] Wallet values are not updating promptly.
- [ ] When they do eventually fire they can go into the negatives.
- [ ] Also impacts trading.

No-Wallet Issues:
- [ ] Change from shops is random.

Shop-Managing:
- [ ] Shop is not reflecting the change right away - requires closing and opening the window.
- [ ] Category listings does not give back money.

Players-Shop:
- [ ] There is no way to extract money as a shop-owner.
- [ ] There is no limit to money in the shop - can create infinite money this way.

**Comment by CarlosEZS** [comment] 2023-05-17 11:09
It's not implemented yet in the workshop version, isn't it?

**Comment by ChuckTheSheep** [comment] 2023-05-17 11:10
No, I am using this for a checklist - this will be closed when completed.

**Comment by ChuckTheSheep** [comment] 2023-05-17 11:10
f7a753b75c0fdcfa8b891a36f16a78beab66f8c4

**Comment by CarlosEZS** [comment] 2023-05-17 11:46
Maybe it's because of the mod Better Sorting?

**Comment by ChuckTheSheep** [comment] 2023-05-17 14:46
Confirmed the issue is better sorting - I had originally written something to avoid this issue, forgot why I wrote it that way ,a nd removed it.

**Comment by CarlosEZS** [comment] 2023-05-19 06:15
Ok good to know.

**Comment by ChuckTheSheep** [comment] 2023-05-20 15:40
Cleaning up the thread for sharing purposes, almost done with the tasks currently set.

**Comment by CarlosEZS** [comment] 2023-05-21 15:44
Just want to add an issue with authentic Z. If you make the craft with the money (don't remember the name) you can make infinite money when you craft it back into vanillia money. Don't know if it's a Authentic Z error or Shop and Trader.

**Comment by ChuckTheSheep** [comment] 2023-05-26 22:00
First pass: https://github.com/ChuckTheSheep/pz-shops/commit/53e54c106369c71c329556a0ef2be586c64e421a

**Comment by alf2812** [comment] 2023-05-27 16:37
getting this error code whenever trying to make a new shop. 
My existing shops still work, but nothing can be added.

`attempted index: ownerID of non-table: false
function: initialise -- file: shop-window.lua line # 490 | MOD: Shops and Traders
function: onBrowse -- file: shop-window.lua line # 1651 | MOD: Shops and Traders
function: browseStore -- file: shop-contextMenu.lua line # 11 | MOD: Shops and Traders
function: onMouseUp -- file: ISContextMenu.lua line # 90 | Vanilla
java.lang.RuntimeException: attempted index: ownerID of non-table: false
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallBoolean(KahluaThread.java:1924)
    at se.krka.kahlua.integration.LuaCaller.protectedCallBoolean(LuaCaller.java:104)
    at zombie.ui.UIElement.onMouseUp(UIElement.java:1228)
    at zombie.ui.UIManager.update(UIManager.java:816)
    at zombie.GameWindow.logic(GameWindow.java:262)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

Juggy

**Comment by ChuckTheSheep** [comment] 2023-05-27 17:16
> 

Thank you, this will be fixed now.

**Comment by alf2812** [comment] 2023-05-30 22:01
`attempted index: getModData of non-table: null
function: testCanScrap -- file: shop-disassembleProtection.lua line # 4 | MOD: Shops and Traders
function: getCanScrapInfoPanelDesc -- file: shop-disassembleProtection.lua line # 41 | MOD: Shops and Traders
function: getInfoPanelDescription -- file: shop-disassembleProtection.lua line # 58 | MOD: Shops and Traders
function: setInfoPanel -- file: ISMoveableCursor.lua line # 213 | Vanilla
function: isValid -- file: ISMoveableCursor.lua line # 379 | Vanilla
function: DoTileBuilding -- file: ISBuildingObject.lua line # 169 | Vanilla
java.lang.RuntimeException: attempted index: getModData of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:299)
    at zombie.iso.IsoCell.doBuildingInternal(IsoCell.java:3467)
    at zombie.iso.IsoCell.DoBuilding(IsoCell.java:3432)
    at zombie.iso.IsoCell.renderInternal(IsoCell.java:5142)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.iso.IsoCell.render(IsoCell.java:4643)
    at zombie.iso.IsoWorld.renderInternal(IsoWorld.java:3281)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.iso.IsoWorld.render(IsoWorld.java:3240)
    at zombie.gameStates.IngameState.renderFrameInternal(IngameState.java:1140)
    at zombie.util.lambda.Invokers$Params2$CallbackStackItem.run(Invokers.java:91)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$1(AbstractPerformanceProfileProbe.java:91)
    at zombie.util.lambda.Stacks$Params4$CallbackStackItem.invoke(Stacks.java:286)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:136)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:89)
    at zombie.gameStates.IngameState.renderframe(IngameState.java:1114)
    at zombie.gameStates.IngameState.renderInternal(IngameState.java:1296)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.gameStates.IngameState.render(IngameState.java:1271)
    at zombie.gameStates.GameStateMachine.render(GameStateMachine.java:37)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.GameWindow.renderInternal(GameWindow.java:340)
    at zombie.GameWindow.frameStep(GameWindow.java:774)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

Getting this error when trying to pick up certain paintings in the world, but not all of them.

Also when you get a minute (i know youre super busy with the player shop stuff)
Would love for you to have a look at the inventory forcibly swapping whenever an item is dragged into it.
Not a priority at all tho. 

Thanks again chuck

**Comment by alf2812** [comment] 2023-05-30 22:04
`java.lang.RuntimeException: attempted index: getModData of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:299)
    at zombie.iso.IsoCell.doBuildingInternal(IsoCell.java:3467)
    at zombie.iso.IsoCell.DoBuilding(IsoCell.java:3432)
    at zombie.iso.IsoCell.renderInternal(IsoCell.java:5142)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.iso.IsoCell.render(IsoCell.java:4643)
    at zombie.iso.IsoWorld.renderInternal(IsoWorld.java:3281)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.iso.IsoWorld.render(IsoWorld.java:3240)
    at zombie.gameStates.IngameState.renderFrameInternal(IngameState.java:1140)
    at zombie.util.lambda.Invokers$Params2$CallbackStackItem.run(Invokers.java:91)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$1(AbstractPerformanceProfileProbe.java:91)
    at zombie.util.lambda.Stacks$Params4$CallbackStackItem.invoke(Stacks.java:286)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:136)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:89)
    at zombie.gameStates.IngameState.renderframe(IngameState.java:1114)
    at zombie.gameStates.IngameState.renderInternal(IngameState.java:1296)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.gameStates.IngameState.render(IngameState.java:1271)
    at zombie.gameStates.GameStateMachine.render(GameStateMachine.java:37)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.GameWindow.renderInternal(GameWindow.java:340)
    at zombie.GameWindow.frameStep(GameWindow.java:774)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

That was also in the logs at the same time,
No idea if its relevant. I dont speak code lol

But it might help :)

**Comment by ChuckTheSheep** [comment] 2023-06-03 18:10
> 

Fixed here: 2ba24117ed6acb6e74ae8b53ee33088f6e39a7cf

**Comment by Chuckleberry-Finn** [comment] 2023-08-17 11:12
#15

**Closed** 2023-08-21 14:14 UTC
